name: CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    # For parallel execution with variable parameters - definition
    # strategy:
    #   matrix:
    #     node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # For parallel execution with variable parameters - usage
    # - name: Set up Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Try to get cached dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

  test:
    needs: [ prepare ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Run the tests
      run: npm test
